<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit602c60cd4d4d4ee819fc1bba7235993f
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'LukZ\\PhpApiTokenAuth\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LukZ\\PhpApiTokenAuth\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit602c60cd4d4d4ee819fc1bba7235993f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit602c60cd4d4d4ee819fc1bba7235993f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit602c60cd4d4d4ee819fc1bba7235993f::$classMap;

        }, null, ClassLoader::class);
    }
}
